version: '3'

services:

  nginx:
    container_name: lks_${ENVIRONMENT}_nginx
    image: nginx:1.19.5-alpine
    restart: always
    depends_on:
      - backend
    volumes:
      - ./static:/static
      - ./media:/media
      - ./nginx.conf.nginx:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf:/etc/letsencrypt/:ro
    env_file: .env
    ports:
      - "${NGINX_PORT}:80"
      - "443:443"

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www:/var/www/certbot/:rw
      - ./certbot/conf:/etc/letsencrypt/:rw

  redis:
    container_name: lks_${ENVIRONMENT}_redis
    image: redis:6.0.9-alpine
    restart: always
    env_file: .env
    command: redis-server --requirepass ${REDIS_PASSWORD}

  postgresql:
    container_name: lks_${ENVIRONMENT}_postgres
    image: postgres:13.1-alpine
    restart: always
    env_file: .env
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data

    healthcheck:
      test: pg_isready -U ${db_user}
      interval: 2s
      timeout: 3s
      retries: 40


  backend:
    container_name: lks_${ENVIRONMENT}_backend
    image: 63phc/lks:latest
    build:
      context: ..
      dockerfile: .docker/Dockerfile
      args:
        env: dev
    restart: always
    command: bash -c "
      gunicorn src.core.wsgi:application -w 2 -b 0.0.0.0:8000"
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    env_file: .env
    depends_on:
      - postgresql
      - redis

  celery:
    container_name: lks_${ENVIRONMENT}_celery
    image: 63phc/lks:latest
    restart: always
    command: bash -c "
      celery -A src.core.celery worker --loglevel=info --uid=nobody --gid=nogroup"
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    env_file: .env
    depends_on:
      - postgresql
      - redis
